version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.9.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MARIADB_DATABASE=VCTG"
      - "MARIADB_USER=user"
      - "MARIADB_PASSWORD=password"
      - "MARIADB_ROOT_PASSWORD=root"
      - "TZ=Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci