version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=vctg
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=vctg-svc
      - MYSQL_PASSWORD=vctg-pass
      - TZ=Asia/Seoul